### ISSUE TITLE
bug: Biography does not update even when edited

### ISSUE THREAD

**Issue by brotherIy** [swmff/sparkler#17] opened 2024-08-25 18:46 UTC
Writing this for a friend since she does not have a GitHub account. No matter how many times she tried to update her biography, nothing changed, even if a completely different sentence was written or if the biography was fully deleted

![Untitled1729_20240825154406](https://github.com/user-attachments/assets/8490d2ee-4972-441e-9a34-62607a8b2fae)

https://github.com/user-attachments/assets/a00aa348-4857-40f4-804f-acdf039642e8

**Comment by trisuaso** [comment] 2024-08-25 19:19
This *appears* to be caused by the characters used in the biography. They cannot be decoded from JSON because they are invalid in JSON and should not have been allowed in the string to start with.

Will be fixed shortly!

**Comment by trisuaso** [comment] 2024-08-25 19:59
Fixed.

**Closed by trisuaso** 2024-08-25 19:59 UTC
Labels: bug
